apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: controller
data:
  compute-full-forwarded-for: "true"
  use-forwarded-headers: "true"
  enable-snippets: "true"
  allow-snippet-annotations: "true"
  annotations-risk-level: "Critical"
