namespace: apps
namePrefix: vaultwarden-

labels:
- includeSelectors: true
  pairs:
    app: vaultwarden
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/part-of: vaultwarden
    app.kubernetes.io/managed-by: kustomize

resources:
- secret.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
# - cronjob.yaml
