namespace: kube-system
namePrefix: sealed-secrets-

labels:
- includeSelectors: true
  pairs:
    app: sealed-secrets
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/part-of: sealed-secrets
    app.kubernetes.io/managed-by: kustomize

resources:
- https://github.com/bitnami-labs/sealed-secrets/raw/refs/tags/v0.34.0/helm/sealed-secrets/crds/bitnami.com_sealedsecrets.yaml
- serviceaccount.yaml
- rbac.yaml
- deployment.yaml
- service.yaml
