namespace: flux

resources:
- sealed-secrets.yaml
- cert-manager.yaml
- external-dns.yaml
- ingress-nginx.yaml
- local-path-provisioner.yaml
- metrics-server.yaml
- descheduler.yaml
- reflector.yaml
- reloader.yaml
- cloudnative-pg.yaml
- prometheus.yaml
