apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
spec:
  interval: 5m
  path: infra/prometheus
  prune: true
  sourceRef:
    kind: GitRepository
    name: prod
