apiVersion: apps/v1
kind: Deployment
metadata:
  name: filter
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  # TODO: scale to 3
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels: {}
            topologyKey: kubernetes.io/hostname
      initContainers:
      - name: configure-postfix
        image: mirror.gcr.io/dibi/envsubst
        command: ["sh", "-c", "envsubst < /template/opendkim.conf.tmpl > /config/opendkim.conf"]
        volumeMounts:
        - name: template
          mountPath: /template
        - name: config
          mountPath: /config
      containers:
        - name: opendkim
          image: mirror.gcr.io/instrumentisto/opendkim:2.11-alpine
          ports:
            - name: milter
              containerPort: 8891
          volumeMounts:
            - name: config
              mountPath: /etc/opendkim/opendkim.conf
              subPath: opendkim.conf
              readOnly: true
            - name: tables
              mountPath: /etc/opendkim/KeyTable
              subPath: KeyTable
              readOnly: true
            - name: tables
              mountPath: /etc/opendkim/SigningTable
              subPath: SigningTable
              readOnly: true
            - name: keys
              mountPath: /etc/opendkim/keys
              readOnly: true
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 64Mi
      volumes:
        - name: template
          configMap:
            name: config
        - name: config
          emptyDir: {}
        - name: tables
          configMap:
            name: config
        - name: keys
          secret:
            secretName: mail-dkim-keys
