apiVersion: v1
kind: Service
metadata:
  name: controller-teapot.ovh
spec:
  selector:
    domain: teapot.ovh
  type: ClusterIP
  ports:
    - name: http
      port: 7979
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: controller-cappuccino.ovh
spec:
  selector:
    domain: teapot.ovh
  type: ClusterIP
  ports:
    - name: http
      port: 7979
      targetPort: http
      protocol: TCP
