apiVersion: v1
kind: Service
metadata:
  name: server
  annotations:
    external-dns.alpha.kubernetes.io/hostname: imap.teapot.ovh
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: imaps
      port: 993
      nodePort: 30993
      targetPort: imaps
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: lmtp
spec:
  # TODO: add back when scale set to 3
  # internalTrafficPolicy: Local
  ports:
    - name: lmtp
      port: 24
      targetPort: lmtp
      protocol: TCP
