apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server
  annotations:
    cert-manager.io/cluster-issuer: "cert-manager-letsencrypt-prod"
    nginx.ingress.kubernetes.io/server-snippet: |
      location ^~ /admin {
        return 403;
      }
spec:
  tls:
  - secretName: teapot-dev-vault-tls
    hosts:
    - vault.prod.teapot.ovh
  rules:
  - host: vault.prod.teapot.ovh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: server
            port:
              number: 80
