apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  # TODO: raise back to 3
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '9154'
    spec:
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels: {}
            topologyKey: kubernetes.io/hostname
        # TODO: remove when smtp is enabled on kube04
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - kube04.prod.infra.teapot.ovh
                - kube03.prod.infra.teapot.ovh
      containers:
        - name: postfix
          image: mirror.gcr.io/instrumentisto/postfix:3.1-alpine
          ports:
            - name: smtp
              containerPort: 25
          volumeMounts:
            - name: config
              mountPath: /etc/syslog.conf
              subPath: syslog.conf
              readOnly: true
            - name: config
              mountPath: /etc/postfix/main.cf
              subPath: main.cf
              readOnly: true
            - name: config
              mountPath: /etc/postfix/sender_access
              subPath: sender_access
              readOnly: true
            - name: config
              mountPath: /etc/postfix/header_checks
              subPath: header_checks
              readOnly: true
            - name: logs
              mountPath: /var/log/postfix
            - name: spool
              mountPath: /var/spool/postfix
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
        - name: postfix-exporter
          image: mirror.gcr.io/unikum/postfix_exporter
          ports:
            - name: metrics
              containerPort: 9154
          volumeMounts:
            - name: logs
              mountPath: /var/log/postfix
              readOnly: true
            - name: spool
              mountPath: /var/spool/postfix
              readOnly: true
          args:
            - --postfix.logfile_path=/var/log/postfix/mail.log
            - --postfix.showq_path=/var/spool/postfix/public/showq
      volumes:
        - name: config
          configMap:
            name: config
        - name: logs
          emptyDir: {}

  volumeClaimTemplates:
    - metadata:
        name: spool
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-path-storageclass"
        resources:
          requests:
            storage: 64Mi
