apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 3
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels: {}
            topologyKey: kubernetes.io/hostname
      containers:
        - name: postfix
          image: instrumentisto/postfix:3.1-alpine
          ports:
            - name: smtp
              containerPort: 25
          volumeMounts:
            - name: config
              mountPath: /etc/postfix
              readOnly: true
            - name: logs
              mountPath: /var/log/postfix
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
        - name: postfix-exporter
          image: sergeymakinen/postfix_exporter:v2.1.0
          ports:
            - name: metrics
              containerPort: 9907
          volumeMounts:
            - name: logs
              mountPath: /var/log/postfix
              readOnly: true
          args:
            - --file.log=/var/log/postfix/postfix.log
      volumes:
        - name: config
          configMap:
            name: config
        - name: logs
          emptyDir: {}
