apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  # TODO: raise back to 3
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '9907'
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels: {}
            topologyKey: kubernetes.io/hostname
        # TODO: remove when smtp is enabled on kube04
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - kube04.prod.infra.teapot.ovh
      containers:
        - name: postfix
          image: instrumentisto/postfix:3.1-alpine
          ports:
            - name: smtp
              containerPort: 25
          volumeMounts:
            - name: config
              mountPath: /etc/syslog.conf
              subPath: syslog.conf
              readOnly: true
            - name: config
              mountPath: /etc/postfix/main.cf
              subPath: main.cf
              readOnly: true
            - name: config
              mountPath: /etc/postfix/sender_access
              subPath: sender_access
              readOnly: true
            - name: config
              mountPath: /etc/postfix/header_checks
              subPath: header_checks
              readOnly: true
            - name: logs
              mountPath: /var/log/postfix
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
        - name: postfix-exporter
          image: sergeymakinen/postfix_exporter:v2.1.0
          ports:
            - name: metrics
              containerPort: 9907
          volumeMounts:
            - name: logs
              mountPath: /var/log/postfix
              readOnly: true
          args:
            - --file.log=/var/log/postfix/mail.log
      volumes:
        - name: config
          configMap:
            name: config
        - name: logs
          emptyDir: {}
