labels:
- includeSelectors: true
  pairs:
    app: cert-manager
    app.kubernetes.io/component: issuer
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-manager


resources:
- letsencrypt-prod.yaml
- letsencrypt-staging.yaml
