apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-configmap
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: spread
        pluginConfig:
        - name: "RemoveDuplicates"
        plugins:
          balance:
            enabled:
              - "RemoveDuplicates"
