namePrefix: descheduler-
namespace: kube-system

labels:
- includeSelectors: true
  pairs:
    app: descheduler
    app.kubernetes.io/instance: descheduler
    app.kubernetes.io/name: descheduler
    app.kubernetes.io/part-of: descheduler
    app.kubernetes.io/managed-by: kustomize

resources:
- rbac.yaml
- configmap.yaml
- deployment.yaml
