apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  "openarc.conf": |
    Syslog yes
    SyslogSuccess yes
    Mode sv

    Domain smtp.teapot.ovh
    KeyFile /etc/openarc/keys/smtp.teapot.ovh.30012026.key
    Selector 30012026

    Canonicalization relaxed/simple
