apiVersion: apps/v1
kind: Deployment
metadata:
  name: filter
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  # TODO: scale to 3
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels: {}
            topologyKey: kubernetes.io/hostname
      initContainers:
        - name: fix-keys
          image: alpine:latest
          command:
            - sh
            - -c
            - |
              cp -r /mnt/keys/* /mnt/fixed-keys/
              chmod 700 /mnt/fixed-keys
              chmod 600 /mnt/fixed-keys/*
          volumeMounts:
            - name: keys
              mountPath: /mnt/keys
              readOnly: true
            - name: fixed-keys
              mountPath: /mnt/fixed-keys
      containers:
        - name: openarc
          image: ghcr.io/teapotovh/openarc:v0.0.8
          ports:
            - name: milter
              containerPort: 8893
          volumeMounts:
            - name: config
              mountPath: /etc/openarc.conf
              subPath: openarc.conf
              readOnly: true
            - name: fixed-keys
              mountPath: /etc/openarc/keys
              readOnly: true
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 64Mi
      volumes:
        - name: config
          configMap:
            name: config
        - name: keys
          secret:
            secretName: mail-arc-keys
        - name: fixed-keys
          emptyDir: {}
