namespace: app
namePrefix: mail-

labels:
- includeSelectors: true
  pairs:
    app: mail
    app.kubernetes.io/name: mail
    app.kubernetes.io/part-of: mail
    app.kubernetes.io/managed-by: kustomize

resources:
- spamassassin
