apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: controller
spec:
  selector:
    app.kubernetes.io/component: controller
  type: NodePort
  internalTrafficPolicy: Local
  externalTrafficPolicy: Local
  ports:
  - appProtocol: http
    name: http
    port: 80
    nodePort: 30080
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    nodePort: 30443
    protocol: TCP
    targetPort: https
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: controller-admission
spec:
  ports:
  - appProtocol: https
    name: https-webhook
    port: 443
    targetPort: webhook
  selector:
    app.kubernetes.io/component: controller
  type: ClusterIP
